-- File in which we build the data structures
-- BC Data and updates courtesy of Dri

gsMine = {
	[gsCopper] = { ["baseskill"]=1 },
	[gsTin] = { ["baseskill"]=65 },
	[gsIncendicite] = { ["baseskill"]=65 },
	[gsSilver] = { ["baseskill"]=75 },
	[gsSilverOz] = { ["baseskill"]=75 },
	[gsLesserBloodstone] = { ["baseskill"]=75 },
	[gsIron] = { ["baseskill"]=125 },
	[gsIndurium] = { ["baseskill"]=150 },
	[gsGold] = { ["baseskill"]=155 },
	[gsGoldOz] = { ["baseskill"]=155 },
	[gsMithril] = { ["baseskill"]=175 },
	[gsMithrilOz] = { ["baseskill"]=175 },
	[gsDarkIron] = { ["baseskill"]=230 },
	[gsTruesilver] = { ["baseskill"]=230 },
	[gsTruesilverOz] = { ["baseskill"]=230 },
	[gsSmallThorium] = { ["baseskill"]=245 },
	[gsThoriumOz] = { ["baseskill"]=245 },
	[gsRichThorium] = { ["baseskill"]=275 },
	[gsRichThoriumOz] = { ["baseskill"]=275 },
	[gsHakkariThorium] = { ["baseskill"]=275 },
	[gsFelIron] = { ["baseskill"]=300 },
	[gsSmallObsidianChunk] = { ["baseskill"]=305 },
	[gsObsidianChunk] = { ["baseskill"]=305 },
	[gsAdamantite] = { ["baseskill"]=325 },
	[gsRichAdamantite] = { ["baseskill"]=350 },
	[gsKhorium] = { ["baseskill"]=375 },
};

gsOre = {
	[gsCopperOre] = { ["baseskill"]=1 },
	[gsTinOre] = { ["baseskill"]=65 },
	[gsSilverOre] = { ["baseskill"]=75 },
	[gsIronOre] = { ["baseskill"]=125 },
	[gsGoldOre] = { ["baseskill"]=155 },
	[gsMithrilOre] = { ["baseskill"]=175 },
	[gsTruesilverOre] = { ["baseskill"]=230 },
	[gsThoriumOre] = { ["baseskill"]=250 },
	[gsDarkIronOre] = { ["baseskill"]=250 },
	[gsElementiumOre] = { ["baseskill"]=300 },
	[gsFelIronOre] = { ["baseskill"]=305 },
	[gsAdamantiteOre] = { ["baseskill"]=325 },
	[gsEterniumOre] = { ["baseskill"]=350 },
	[gsKhoriumOre] = { ["baseskill"]=375 },
};

gsGem = {
	[gsTigerseye] = gsCopper.."/"..gsTin,
};

gsStone = {
	[gsRoughStone] = gsCopper,
	[gsCoarseStone] = gsTin,
	[gsHeavy] = gsIron,
	[gsSolid] = {gsMithril,gsMithrilOz},
	[gsDense] = {gsSmallThorium,gsRichThorium,gsThoriumOz,gsRichThoriumOz,gsHakkariThorium},
	[gsMoteEarth] = {gsFelIron,gsAdamantite,gsRichAdamantite,gsKhorium},
	[gsMoteFire] = gsFelIron,
};

gsMineHasStone = {
	[gsCopper] = gsRoughStone,
	[gsTin] = gsCoarseStone,
	[gsIron] = gsHeavy,
	[gsMithril] = gsSolid,
	[gsMithrilOz] = gsSolid,
	[gsSmallThorium] = gsDense,
	[gsRichThorium] = gsDense,
	[gsThoriumOz] = gsDense,
	[gsRichThoriumOz] = gsDense,
	[gsHakkariThorium] = gsDense,
	[gsFelIron] = gsMoteEarth,
	[gsAdamantite] = gsMoteEarth,
	[gsRichAdamantite] = gsMoteEarth,
	[gsKhorium] = gsMoteEarth,
};

gsMineHasGem = {
	[gsCopper] = {[1]=gsTigerseye,[2]=gsMalachite,[3]=gsShadowgem},
	[gsTin] = {[1]=gsMossAgate,[2]=gsShadowgem,[3]=gsLesserMoonstone,[4]=gsJade},
	[gsSilver] = {[1]=gsMossAgate,[2]=gsShadowgem,[3]=gsLesserMoonstone},
	[gsIron] = {[1]=gsJade,[2]=gsLesserMoonstone,[3]=gsCitrine,[4]=gsAquamarine},
	[gsGold] = {[1]=gsJade,[2]=gsCitrine,[3]=gsLesserMoonstone},
	[gsMithril] = {[1]=gsBlackVitriol,[2]=gsAquamarine,[3]=gsCitrine,[4]=gsStarRuby},
	[gsTruesilver] = {[1]=gsAquamarine,[2]=gsStarRuby,[3]=gsCitrine},
	[gsSmallThorium] = {[1]=gsBlackVitriol,[2]=gsStarRuby,[3]=gsLargeOpal,[4]=gsBlueSapphire,[5]=gsHugeEmerald,[6]=gsAzerothianDiamond},
	[gsRichThorium] = {[1]=gsArcaneCrystal,[2]=gsBlueSapphire,[3]=gsStarRuby,[4]=gsAzerothianDiamond,[5]=gsHugeEmerald,[6]=gsLargeOpal},
	[gsDarkIron] = {[1]=gsBlackVitriol,[2]=gsBloodoftheMountain,[3]=gsBlackDiamond},
	[gsObsidianChunk] = {[1]=gsHugeEmerald,[2]=gsAzerothianDiamond,[3]=gsArcaneCrystal},
	[gsSmallObsidianChunk] = {[1]=gsHugeEmerald,[2]=gsAzerothianDiamond,[3]=gsArcaneCrystal},
	[gsSilverOz] = {[1]=gsMossAgate,[2]=gsShadowgem,[3]=gsLesserMoonstone},
	[gsGoldOz] = {[1]=gsJade,[2]=gsCitrine,[3]=gsLesserMoonstone},
	[gsMithrilOz] = {[1]=gsBlackVitriol,[2]=gsAquamarine,[3]=gsCitrine,[4]=gsStarRuby},
	[gsTruesilverOz] = {[1]=gsAquamarine,[2]=gsStarRuby,[3]=gsCitrine},
	[gsThoriumOz] = {[1]=gsBlackVitriol,[2]=gsStarRuby,[3]=gsLargeOpal,[4]=gsBlueSapphire,[5]=gsHugeEmerald,[6]=gsAzerothianDiamond},
	[gsRichThoriumOz] = {[1]=gsArcaneCrystal,[2]=gsBlueSapphire,[3]=gsStarRuby,[4]=gsAzerothianDiamond,[5]=gsHugeEmerald,[6]=gsLargeOpal},
	[gsHakkariThorium] = {[1]=gsSouldarite,[2]=gsArcaneCrystal,[3]=gsHugeEmerald,[4]=gsAzerothianDiamond,[5]=gsStarRuby,[6]=gsBlueSapphire,[7]=gsLargeOpal},
	[gsFelIron] = {[1]=gsShadowDraenite,[2]=gsDeepPeridot,[3]=gsFlameSpessarite,[4]=gsBloodGarnet,[5]=gsGoldenDraenite,[6]=gsAzureMoonstone,[7]=gsLivingRuby},
	[gsAdamantite] = {[1]=gsArcaneCrystal,[2]=gsBloodGarnet,[3]=gsGoldenDraenite,[4]=gsAzureMoonstone,[5]=gsLivingRuby,[6]=gsTalasite,[7]=gsNightseye},
	[gsRichAdamantite] = {[1]=gsArcaneCrystal,[2]=gsAzureMoonstone,[3]=gsGoldenDraenite,[4]=gsBloodGarnet,[5]=gsShadowDraenite,[6]=gsFlameSpessarite,[7]=gsDeepPeridot,[8]=gsNobleTopaz,[9]=gsLivingRuby},
	[gsKhorium] = {[1]=gsArcaneCrystal,[2]=gsAzureMoonstone,[3]=gsGoldenDraenite,[4]=gsBloodGarnet,[5]=gsShadowDraenite,[6]=gsFlameSpessarite,[7]=gsDeepPeridot,[8]=gsNobleTopaz,[9]=gsLivingRuby},
};

gsHerbHasHerb = {
	[gsMageroyal] = gsSwiftThistle,
	[gsBriarthorn] = gsSwiftThistle,
	[gsPurpleLotus] = gsWildvine,
	[gsFelweed] = gsFelBlossom,
	[gsDreamingGlory] = gsUnPlantParts,
	[gsRagveil] = gsUnPlantParts,
	[gsNightmareVine] = gsNightmareSeed,
};

gsHerb = {
	[gsPeacebloom] = { ["baseskill"]=1 },
	[gsSilverleaf] = { ["baseskill"]=1 },
	[gsEarthroot] = { ["baseskill"]=15 },
	[gsMageroyal] = { ["baseskill"]=50 },
	[gsBriarthorn] = { ["baseskill"]=70 },
	[gsStranglekelp] = { ["baseskill"]=85 },
	[gsBruiseweed] = { ["baseskill"]=100 },
	[gsWildSteelbloom] = { ["baseskill"]=115 },
	[gsGraveMoss] = { ["baseskill"]=120 },
	[gsKingsblood] = { ["baseskill"]=125 },
	[gsLiferoot] = { ["baseskill"]=150 },
	[gsFadeleaf] = { ["baseskill"]=160 },
	[gsGoldthorn] = { ["baseskill"]=170 },
	[gsKhadgar] = { ["baseskill"]=185 },
	[gsWintersbite] = { ["baseskill"]=195 },
	[gsFirebloom] = { ["baseskill"]=205 },
	[gsPurpleLotus] = { ["baseskill"]=210 },
	[gsArthas] = { ["baseskill"]=220 },
	[gsSungrass] = { ["baseskill"]=230 },
	[gsBlindweed] = { ["baseskill"]=235 },
	[gsGhostMushroom] = { ["baseskill"]=245 },
	[gsGromsblood] = { ["baseskill"]=250 },
	[gsGoldenSansam] = { ["baseskill"]=260 },
	[gsDreamfoil] = { ["baseskill"]=270 },
	[gsMountainSilversage] = { ["baseskill"]=280 },
	[gsPlaguebloom] = { ["baseskill"]=285 },
	[gsIcecap] = { ["baseskill"]=290 },
	[gsBlackLotus] = { ["baseskill"]=300 },
	[gsFelweed] = { ["baseskill"]=300 },
	[gsDreamingGlory] = { ["baseskill"]=315 },
	[gsRagveil] = { ["baseskill"]=325 },
	[gsFlameCap] = { ["baseskill"]=335 },
	[gsTerocone] = { ["baseskill"]=325 },
	[gsAncientLichen] = { ["baseskill"]=340 },
	[gsManaThistle] = { ["baseskill"]=375 },
	[gsNetherbloom] = { ["baseskill"]=350 },
	[gsNightmareVine] = { ["baseskill"]=365 },
};
